//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using Pns.Globals;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 

namespace Pns.Xml_Serialization.PnsProblem
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/PNSXMLSchema")]
    [System.Xml.Serialization.XmlRootAttribute("pns", Namespace = "http://www.example.org/PNSXMLSchema", IsNullable = false)]
    public partial class PNS
    {

        private Header headerField;

        private Problem problemField;

        private Solution[] solutionField;

        private LayoutInfo layoutinfoField;

        /// <remarks/>
        public Header header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }

        /// <remarks/>
        public Problem problem
        {
            get
            {
                return this.problemField;
            }
            set
            {
                this.problemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("solution")]
        public Solution[] solution
        {
            get
            {
                return this.solutionField;
            }
            set
            {
                this.solutionField = value;
            }
        }

        /// <remarks/>
        public LayoutInfo layoutinfo
        {
            get
            {
                return this.layoutinfoField;
            }
            set
            {
                this.layoutinfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/PNSXMLSchema")]
    public partial class Header
    {

        private string authorField;

        private string descriptionField;

        private string versionField;

        private System.DateTime dateField;

        private bool dateFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified
        {
            get
            {
                return this.dateFieldSpecified;
            }
            set
            {
                this.dateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/PNSXMLSchema")]
    public partial class Bendpoint
    {

        private string fromField;

        private string toField;

        private int indexField;

        private bool indexFieldSpecified;

        private int posXField;

        private bool posXFieldSpecified;

        private int posYField;

        private bool posYFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indexSpecified
        {
            get
            {
                return this.indexFieldSpecified;
            }
            set
            {
                this.indexFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int posX
        {
            get
            {
                return this.posXField;
            }
            set
            {
                this.posXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool posXSpecified
        {
            get
            {
                return this.posXFieldSpecified;
            }
            set
            {
                this.posXFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int posY
        {
            get
            {
                return this.posYField;
            }
            set
            {
                this.posYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool posYSpecified
        {
            get
            {
                return this.posYFieldSpecified;
            }
            set
            {
                this.posYFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/PNSXMLSchema")]
    public partial class LayoutInfo
    {

        private Bendpoint[] bendpointsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("bendpoint", IsNullable = false)]
        public Bendpoint[] bendpoints
        {
            get
            {
                return this.bendpointsField;
            }
            set
            {
                this.bendpointsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/PNSXMLSchema")]
    public partial class SolutionMaterial
    {

        private Layout layoutField;

        private string nameField;

        /// <remarks/>
        public Layout layout
        {
            get
            {
                return this.layoutField;
            }
            set
            {
                this.layoutField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/PNSXMLSchema")]
    public partial class Layout
    {

        private int posXField;

        private int posYField;

        private System.Xml.XmlAttribute[] anyAttrField;

        private int labelXField;

        private bool labelXFieldSpecified;

        private int labelYField;

        private bool labelYFieldSpecified;

        public Layout()
        {
            this.posXField = 0;
            this.posYField = 0;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int posX
        {
            get
            {
                return this.posXField;
            }
            set
            {
                this.posXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int posY
        {
            get
            {
                return this.posYField;
            }
            set
            {
                this.posYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int labelX
        {
            get
            {
                return this.labelXField;
            }
            set
            {
                this.labelXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool labelXSpecified
        {
            get
            {
                return this.labelXFieldSpecified;
            }
            set
            {
                this.labelXFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int labelY
        {
            get
            {
                return this.labelYField;
            }
            set
            {
                this.labelYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool labelYSpecified
        {
            get
            {
                return this.labelYFieldSpecified;
            }
            set
            {
                this.labelYFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/PNSXMLSchema")]
    public partial class SolutionOperatingUnit
    {

        private Layout layoutField;

        private double capacityField;

        private bool capacityFieldSpecified;

        private int piecesField;

        private string nameField;

        public SolutionOperatingUnit()
        {
            this.piecesField = 1;
        }

        /// <remarks/>
        public Layout layout
        {
            get
            {
                return this.layoutField;
            }
            set
            {
                this.layoutField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double capacity
        {
            get
            {
                return this.capacityField;
            }
            set
            {
                this.capacityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool capacitySpecified
        {
            get
            {
                return this.capacityFieldSpecified;
            }
            set
            {
                this.capacityFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1)]
        public int pieces
        {
            get
            {
                return this.piecesField;
            }
            set
            {
                this.piecesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/PNSXMLSchema")]
    public partial class Solution
    {

        private SolutionOperatingUnit[] solutionOperatingUnitField;

        private SolutionMaterial[] solutionMaterialField;

        private string algorithmField;

        private int currentStepField;

        private bool currentStepFieldSpecified;

        private int maxStepField;

        private bool maxStepFieldSpecified;

        private string optimalValueField;

        private int nthBestField;

        private bool nthBestFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("solutionOperatingUnit")]
        public SolutionOperatingUnit[] solutionOperatingUnit
        {
            get
            {
                return this.solutionOperatingUnitField;
            }
            set
            {
                this.solutionOperatingUnitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("solutionMaterial")]
        public SolutionMaterial[] solutionMaterial
        {
            get
            {
                return this.solutionMaterialField;
            }
            set
            {
                this.solutionMaterialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string algorithm
        {
            get
            {
                return this.algorithmField;
            }
            set
            {
                this.algorithmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int currentStep
        {
            get
            {
                return this.currentStepField;
            }
            set
            {
                this.currentStepField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currentStepSpecified
        {
            get
            {
                return this.currentStepFieldSpecified;
            }
            set
            {
                this.currentStepFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int maxStep
        {
            get
            {
                return this.maxStepField;
            }
            set
            {
                this.maxStepField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxStepSpecified
        {
            get
            {
                return this.maxStepFieldSpecified;
            }
            set
            {
                this.maxStepFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string optimalValue
        {
            get
            {
                return this.optimalValueField;
            }
            set
            {
                this.optimalValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int nthBest
        {
            get
            {
                return this.nthBestField;
            }
            set
            {
                this.nthBestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nthBestSpecified
        {
            get
            {
                return this.nthBestFieldSpecified;
            }
            set
            {
                this.nthBestFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/PNSXMLSchema")]
    public partial class MutualExclusionOperatingUnit
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/PNSXMLSchema")]
    public partial class MutualExclusionSet
    {

        private MutualExclusionOperatingUnit[] mutualExclusionOperatingUnitField;

        private int maxEnabledOperatingUnitsField;

        public MutualExclusionSet()
        {
            this.maxEnabledOperatingUnitsField = 1;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mutualExclusionOperatingUnit")]
        public MutualExclusionOperatingUnit[] mutualExclusionOperatingUnit
        {
            get
            {
                return this.mutualExclusionOperatingUnitField;
            }
            set
            {
                this.mutualExclusionOperatingUnitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1)]
        public int maxEnabledOperatingUnits
        {
            get
            {
                return this.maxEnabledOperatingUnitsField;
            }
            set
            {
                this.maxEnabledOperatingUnitsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/PNSXMLSchema")]
    public partial class FlowMaterial
    {

        private Layout layoutField;

        private double rateField;

        private string flowRateMuField;

        private string nameField;

        /// <remarks/>
        public Layout layout
        {
            get
            {
                return this.layoutField;
            }
            set
            {
                this.layoutField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double rate
        {
            get
            {
                return this.rateField;
            }
            set
            {
                this.rateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string flowRateMu
        {
            get
            {
                return this.flowRateMuField;
            }
            set
            {
                this.flowRateMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/PNSXMLSchema")]
    public partial class OperatingUnit
    {

        private FlowMaterial[] inputMaterialField;

        private FlowMaterial[] outputMaterialField;

        private Layout layoutField;

        private double totalFixField;

        private double totalPropField;

        private double investmentFixField;

        private bool investmentFixFieldSpecified;

        private double investmentPropField;

        private bool investmentPropFieldSpecified;

        private double operatingFixField;

        private bool operatingFixFieldSpecified;

        private double operatingPropField;

        private bool operatingPropFieldSpecified;

        private double lowerBoundField;

        private bool lowerBoundFieldSpecified;

        private double upperBoundField;

        private bool upperBoundFieldSpecified;

        private string fixedChargeMuField;

        private string propConstantMuField;

        private string nameField;

        public OperatingUnit()
        {
            this.totalFixField = def_Values.d_NperA;
            this.totalPropField = def_Values.d_NperA;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inputMaterial")]
        public FlowMaterial[] inputMaterial
        {
            get
            {
                return this.inputMaterialField;
            }
            set
            {
                this.inputMaterialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("outputMaterial")]
        public FlowMaterial[] outputMaterial
        {
            get
            {
                return this.outputMaterialField;
            }
            set
            {
                this.outputMaterialField = value;
            }
        }

        /// <remarks/>
        public Layout layout
        {
            get
            {
                return this.layoutField;
            }
            set
            {
                this.layoutField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double totalFix
        {
            get
            {
                return this.totalFixField;
            }
            set
            {
                this.totalFixField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double totalProp
        {
            get
            {
                return this.totalPropField;
            }
            set
            {
                this.totalPropField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double investmentFix
        {
            get
            {
                return this.investmentFixField;
            }
            set
            {
                this.investmentFixField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool investmentFixSpecified
        {
            get
            {
                return this.investmentFixFieldSpecified;
            }
            set
            {
                this.investmentFixFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double investmentProp
        {
            get
            {
                return this.investmentPropField;
            }
            set
            {
                this.investmentPropField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool investmentPropSpecified
        {
            get
            {
                return this.investmentPropFieldSpecified;
            }
            set
            {
                this.investmentPropFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double operatingFix
        {
            get
            {
                return this.operatingFixField;
            }
            set
            {
                this.operatingFixField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatingFixSpecified
        {
            get
            {
                return this.operatingFixFieldSpecified;
            }
            set
            {
                this.operatingFixFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double operatingProp
        {
            get
            {
                return this.operatingPropField;
            }
            set
            {
                this.operatingPropField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatingPropSpecified
        {
            get
            {
                return this.operatingPropFieldSpecified;
            }
            set
            {
                this.operatingPropFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double lowerBound
        {
            get
            {
                return this.lowerBoundField;
            }
            set
            {
                this.lowerBoundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lowerBoundSpecified
        {
            get
            {
                return this.lowerBoundFieldSpecified;
            }
            set
            {
                this.lowerBoundFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double upperBound
        {
            get
            {
                return this.upperBoundField;
            }
            set
            {
                this.upperBoundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool upperBoundSpecified
        {
            get
            {
                return this.upperBoundFieldSpecified;
            }
            set
            {
                this.upperBoundFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fixedChargeMu
        {
            get
            {
                return this.fixedChargeMuField;
            }
            set
            {
                this.fixedChargeMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string propConstantMu
        {
            get
            {
                return this.propConstantMuField;
            }
            set
            {
                this.propConstantMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/PNSXMLSchema")]
    public partial class ProductMaterial
    {

        private Layout layoutField;

        private double minField;

        private double maxField;

        private double priceField;

        private string requiredFlowMuField;

        private string maximumFlowMuField;

        private string priceMuField;

        private string nameField;

        public ProductMaterial()
        {
            this.minField = def_Values.d_NperA;
            this.maxField = def_Values.d_NperA;
            this.priceField = def_Values.d_NperA;
        }

        /// <remarks/>
        public Layout layout
        {
            get
            {
                return this.layoutField;
            }
            set
            {
                this.layoutField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double min
        {
            get
            {
                return this.minField;
            }
            set
            {
                this.minField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double max
        {
            get
            {
                return this.maxField;
            }
            set
            {
                this.maxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string requiredFlowMu
        {
            get
            {
                return this.requiredFlowMuField;
            }
            set
            {
                this.requiredFlowMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maximumFlowMu
        {
            get
            {
                return this.maximumFlowMuField;
            }
            set
            {
                this.maximumFlowMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string priceMu
        {
            get
            {
                return this.priceMuField;
            }
            set
            {
                this.priceMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/PNSXMLSchema")]
    public partial class IntermediateMaterial
    {

        private Layout layoutField;

        private double maxField;

        private double penaltyField;

        private bool penaltyFieldSpecified;

        private string requiredFlowMuField;

        private string maximumFlowMuField;

        private string nameField;

        public IntermediateMaterial()
        {
            this.maxField = def_Values.d_NperA;
        }

        /// <remarks/>
        public Layout layout
        {
            get
            {
                return this.layoutField;
            }
            set
            {
                this.layoutField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double max
        {
            get
            {
                return this.maxField;
            }
            set
            {
                this.maxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double penalty
        {
            get
            {
                return this.penaltyField;
            }
            set
            {
                this.penaltyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool penaltySpecified
        {
            get
            {
                return this.penaltyFieldSpecified;
            }
            set
            {
                this.penaltyFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string requiredFlowMu
        {
            get
            {
                return this.requiredFlowMuField;
            }
            set
            {
                this.requiredFlowMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maximumFlowMu
        {
            get
            {
                return this.maximumFlowMuField;
            }
            set
            {
                this.maximumFlowMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/PNSXMLSchema")]
    public partial class RawMaterial
    {

        private Layout layoutField;

        private double minField;

        private double maxField;

        private double priceField;

        private string requiredFlowMuField;

        private string maximumFlowMuField;

        private string priceMuField;

        private string nameField;

        public RawMaterial()
        {
            this.minField = def_Values.d_NperA;
            this.maxField = def_Values.d_NperA;
            this.priceField = def_Values.d_NperA;
        }

        /// <remarks/>
        public Layout layout
        {
            get
            {
                return this.layoutField;
            }
            set
            {
                this.layoutField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double min
        {
            get
            {
                return this.minField;
            }
            set
            {
                this.minField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double max
        {
            get
            {
                return this.maxField;
            }
            set
            {
                this.maxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string requiredFlowMu
        {
            get
            {
                return this.requiredFlowMuField;
            }
            set
            {
                this.requiredFlowMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maximumFlowMu
        {
            get
            {
                return this.maximumFlowMuField;
            }
            set
            {
                this.maximumFlowMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string priceMu
        {
            get
            {
                return this.priceMuField;
            }
            set
            {
                this.priceMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/PNSXMLSchema")]
    public partial class Materials
    {

        private RawMaterial[] rawMaterialField;

        private IntermediateMaterial[] intermediateMaterialField;

        private ProductMaterial[] productMaterialField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rawMaterial")]
        public RawMaterial[] rawMaterial
        {
            get
            {
                return this.rawMaterialField;
            }
            set
            {
                this.rawMaterialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("intermediateMaterial")]
        public IntermediateMaterial[] intermediateMaterial
        {
            get
            {
                return this.intermediateMaterialField;
            }
            set
            {
                this.intermediateMaterialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("productMaterial")]
        public ProductMaterial[] productMaterial
        {
            get
            {
                return this.productMaterialField;
            }
            set
            {
                this.productMaterialField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/PNSXMLSchema")]
    public partial class Problem
    {

        private Materials materialsField;

        private OperatingUnit[] operatingUnitsField;

        private MutualExclusionSet[] mutualExclusionSetsField;

        private string massMuField;

        private string timeMuField;

        private string currencyMuField;

        private double payoutPeriodField;

        private int workingHoursPerYearField;

        private string requiredRawFlowMuField;

        private string requiredIntermediateFlowMuField;

        private string requiredProductFlowMuField;

        private string maximumRawFlowMuField;

        private string maximumIntermediateFlowMuField;

        private string maximumProductFlowMuField;

        private string priceMuField;

        private string flowRateMuField;

        private double lowerBoundField;

        private double upperBoundField;

        private double fixedChargeField;

        private double propConstantField;

        private double iFixedChargeField;

        private double iPropConstantField;

        public Problem()
        {
            this.massMuField = "t";
            this.timeMuField = "yr";
            this.currencyMuField = "€";
            this.payoutPeriodField = def_Values.d_NperA;
            this.workingHoursPerYearField = (int)def_Values.d_NperA;
            this.requiredRawFlowMuField = "t/yr";
            this.requiredIntermediateFlowMuField = "t/yr";
            this.requiredProductFlowMuField = "t/yr";
            this.maximumRawFlowMuField = "t/yr";
            this.maximumIntermediateFlowMuField = "t/yr";
            this.maximumProductFlowMuField = "t/yr";
            this.priceMuField = "€/t";
            this.flowRateMuField = "t/yr";
            this.lowerBoundField = def_Values.d_NperA;
            this.upperBoundField = def_Values.d_NperA;
            this.fixedChargeField = def_Values.d_NperA;
            this.propConstantField = def_Values.d_NperA;
            this.iFixedChargeField = def_Values.d_NperA;
            this.iPropConstantField = def_Values.d_NperA;
        }

        /// <remarks/>
        public Materials materials
        {
            get
            {
                return this.materialsField;
            }
            set
            {
                this.materialsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("operatingUnit", IsNullable = false)]
        public OperatingUnit[] operatingUnits
        {
            get
            {
                return this.operatingUnitsField;
            }
            set
            {
                this.operatingUnitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("mutualExclusionSet", IsNullable = false)]
        public MutualExclusionSet[] mutualExclusionSets
        {
            get
            {
                return this.mutualExclusionSetsField;
            }
            set
            {
                this.mutualExclusionSetsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("t")]
        public string massMu
        {
            get
            {
                return this.massMuField;
            }
            set
            {
                this.massMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("yr")]
        public string timeMu
        {
            get
            {
                return this.timeMuField;
            }
            set
            {
                this.timeMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("€")]
        public string currencyMu
        {
            get
            {
                return this.currencyMuField;
            }
            set
            {
                this.currencyMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double payoutPeriod
        {
            get
            {
                return this.payoutPeriodField;
            }
            set
            {
                this.payoutPeriodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public int workingHoursPerYear
        {
            get
            {
                return this.workingHoursPerYearField;
            }
            set
            {
                this.workingHoursPerYearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("t/yr")]
        public string requiredRawFlowMu
        {
            get
            {
                return this.requiredRawFlowMuField;
            }
            set
            {
                this.requiredRawFlowMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("t/yr")]
        public string requiredIntermediateFlowMu
        {
            get
            {
                return this.requiredIntermediateFlowMuField;
            }
            set
            {
                this.requiredIntermediateFlowMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("t/yr")]
        public string requiredProductFlowMu
        {
            get
            {
                return this.requiredProductFlowMuField;
            }
            set
            {
                this.requiredProductFlowMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("t/yr")]
        public string maximumRawFlowMu
        {
            get
            {
                return this.maximumRawFlowMuField;
            }
            set
            {
                this.maximumRawFlowMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("t/yr")]
        public string maximumIntermediateFlowMu
        {
            get
            {
                return this.maximumIntermediateFlowMuField;
            }
            set
            {
                this.maximumIntermediateFlowMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("t/yr")]
        public string maximumProductFlowMu
        {
            get
            {
                return this.maximumProductFlowMuField;
            }
            set
            {
                this.maximumProductFlowMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("€/t")]
        public string priceMu
        {
            get
            {
                return this.priceMuField;
            }
            set
            {
                this.priceMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("t/yr")]
        public string flowRateMu
        {
            get
            {
                return this.flowRateMuField;
            }
            set
            {
                this.flowRateMuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double lowerBound
        {
            get
            {
                return this.lowerBoundField;
            }
            set
            {
                this.lowerBoundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double upperBound
        {
            get
            {
                return this.upperBoundField;
            }
            set
            {
                this.upperBoundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double fixedCharge
        {
            get
            {
                return this.fixedChargeField;
            }
            set
            {
                this.fixedChargeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double propConstant
        {
            get
            {
                return this.propConstantField;
            }
            set
            {
                this.propConstantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double iFixedCharge
        {
            get
            {
                return this.iFixedChargeField;
            }
            set
            {
                this.iFixedChargeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(def_Values.d_NperA)]
        public double iPropConstant
        {
            get
            {
                return this.iPropConstantField;
            }
            set
            {
                this.iPropConstantField = value;
            }
        }
    }
}